[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "damast-sigspatial2026"
version = "0.1.1"
description = "A reproduction package for ACM SIGSPATIAL 2026"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.12"
authors = [
    { name = "Thomas Roehr", email = "roehr@simula.no" },
]
dependencies = [
    "damast[ml]>=0.3.5",
    "pyyaml",
    "healpix",
    "plotly"
]

[dependency-groups]
dev = [
    "pre-commit",
    {include-group = "test"}
]
test = [
    "pytest"
]

# This is what makes transformers in this plugin discoverable for damast.
# After installation, listable with `damast plugins`
[project.entry-points."damast.transformers"]
damast_sigspatial2026 = "damast_sigspatial2026.transformers"

[tool.setuptools.packages.find]
where = ["src"]
